ALTER TYPE "GaraVendorPayoutStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';

ALTER TABLE "GaraVendorPayoutRequest"
  ALTER COLUMN "creditAccountId" DROP NOT NULL,
  ALTER COLUMN "ledgerEntryId" DROP NOT NULL,
  ALTER COLUMN "status" SET DEFAULT 'PENDING_APPROVAL',
  ADD COLUMN "processedAt" TIMESTAMP(3);
