CREATE TABLE "Listing" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT,
    "ownerEmail" TEXT,
    "ownerName" TEXT,
    "title" TEXT NOT NULL,
    "headline" TEXT NOT NULL DEFAULT '',
    "registeredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" TEXT NOT NULL DEFAULT '거래중',
    "viewCount" INTEGER NOT NULL DEFAULT 0,
    "tradeType" TEXT NOT NULL,
    "depositManwon" INTEGER NOT NULL DEFAULT 0,
    "monthlyRentManwon" INTEGER NOT NULL DEFAULT 0,
    "salePriceManwon" INTEGER NOT NULL DEFAULT 0,
    "maintenanceManwon" INTEGER NOT NULL DEFAULT 0,
    "maintenanceIncludes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "loanManwon" INTEGER NOT NULL DEFAULT 0,
    "availableFrom" TEXT NOT NULL DEFAULT '즉시',
    "contractMonths" INTEGER NOT NULL DEFAULT 24,
    "kind" TEXT NOT NULL,
    "areaExclusiveM2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "areaSupplyM2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "floor" INTEGER NOT NULL DEFAULT 1,
    "totalFloors" INTEGER NOT NULL DEFAULT 1,
    "rooms" INTEGER NOT NULL DEFAULT 1,
    "bathrooms" INTEGER NOT NULL DEFAULT 1,
    "direction" TEXT NOT NULL DEFAULT '',
    "buildYear" INTEGER NOT NULL DEFAULT 0,
    "parking" BOOLEAN NOT NULL DEFAULT false,
    "elevator" BOOLEAN NOT NULL DEFAULT false,
    "heating" TEXT NOT NULL DEFAULT '',
    "address" TEXT NOT NULL,
    "jibunAddress" TEXT NOT NULL DEFAULT '',
    "dong" TEXT NOT NULL DEFAULT '',
    "lawdCd" TEXT NOT NULL DEFAULT '',
    "lat" DOUBLE PRECISION NOT NULL DEFAULT 37.5665,
    "lng" DOUBLE PRECISION NOT NULL DEFAULT 126.978,
    "nearestStation" TEXT NOT NULL DEFAULT '',
    "walkMinutes" INTEGER NOT NULL DEFAULT 0,
    "options" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "petsAllowed" BOOLEAN NOT NULL DEFAULT false,
    "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "coverImage" TEXT NOT NULL DEFAULT '',
    "gallery" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "tourId" TEXT,
    "registrantType" TEXT NOT NULL DEFAULT '집주인',
    "brokerName" TEXT NOT NULL DEFAULT '',
    "contactPhone" TEXT NOT NULL DEFAULT '',
    "responseMinutes" INTEGER NOT NULL DEFAULT 0,
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "reviewStatus" TEXT NOT NULL DEFAULT '등록',
    "safetyScore" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Listing_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "Listing_ownerId_idx" ON "Listing"("ownerId");
CREATE INDEX "Listing_ownerEmail_idx" ON "Listing"("ownerEmail");
CREATE INDEX "Listing_kind_tradeType_idx" ON "Listing"("kind", "tradeType");
CREATE INDEX "Listing_lawdCd_idx" ON "Listing"("lawdCd");
CREATE INDEX "Listing_createdAt_idx" ON "Listing"("createdAt");
