import type {
  MoveinRecord,
  ChecklistItem,
  ItemRecord,
} from "@roomlog/types";

// 입주기록 슬라이스 데모 시드 — api(인메모리 리포)와 동일한 값으로 맞춘다(BE·FE 공용 기준값).
// 화면이 api 없이도 렌더되도록 프론트 폴백으로도 쓰인다.
// 오늘=2026-07-01 기준: 입주일 06-30 → 잠금 윈도우(입주 +72h) 06-30~07-03 = 현재 윈도우 내(1급).

export const DEMO_LEASE_ID = "ls_0001";

export const DEMO_MOVEIN: MoveinRecord = {
  leaseId: DEMO_LEASE_ID,
  unitId: "302",
  checklistVersion: "cl_v1",
  moveinDate: "2026-06-30T00:00:00+09:00",
  lockWindowStartAt: "2026-06-30T00:00:00+09:00",
  lockWindowEndAt: "2026-07-03T00:00:00+09:00",
  capturedCount: 3, // 누적(분모 숨김) — 아래 촬영된 item 3개와 일치
};

// 확인 항목(체크리스트 정의) — 핵심 먼저(고가·누수) + 권장(접힘). 표준 코드+다국어.
export const DEMO_CHECKLIST: ChecklistItem[] = [
  {
    id: "item_aircon",
    spaceId: "space_living",
    spaceLabel: "거실",
    label: "에어컨",
    labelI18n: { ko: "에어컨", en: "Air conditioner", zh: "空调", vi: "Máy lạnh" },
    icon: "❄️",
    sourceTier: "contract_option",
    contractLabel: "벽걸이 에어컨(LG)",
    isCore: true,
    coreReason: "고가 옵션",
  },
  {
    id: "item_fridge",
    spaceId: "space_kitchen",
    spaceLabel: "주방",
    label: "빌트인 냉장고",
    labelI18n: { ko: "빌트인 냉장고", en: "Built-in fridge", zh: "嵌入式冰箱", vi: "Tủ lạnh âm tủ" },
    icon: "🧊",
    sourceTier: "contract_option",
    contractLabel: "빌트인 냉장고",
    isCore: true,
    coreReason: "고가 옵션",
  },
  {
    id: "item_sink",
    spaceId: "space_kitchen",
    spaceLabel: "주방",
    label: "싱크대 하부",
    labelI18n: { ko: "싱크대 하부", en: "Under-sink", zh: "水槽下方", vi: "Dưới bồn rửa" },
    icon: "🚰",
    sourceTier: "standard_fallback",
    fallbackItemId: "std_sink",
    isCore: true,
    coreReason: "누수 잦은 곳",
  },
  {
    id: "item_bath_drain",
    spaceId: "space_bath",
    spaceLabel: "욕실",
    label: "화장실 배수구",
    labelI18n: { ko: "화장실 배수구", en: "Bathroom drain", zh: "浴室排水口", vi: "Cống thoát nước" },
    icon: "🚿",
    sourceTier: "standard_fallback",
    fallbackItemId: "std_bath_drain",
    isCore: true,
    coreReason: "누수 잦은 곳",
  },
  {
    id: "item_wallpaper",
    spaceId: "space_living",
    spaceLabel: "거실",
    label: "벽지·도배",
    labelI18n: { ko: "벽지·도배", en: "Wallpaper", zh: "墙纸", vi: "Giấy dán tường" },
    icon: "🧱",
    sourceTier: "standard_fallback",
    fallbackItemId: "std_wallpaper",
    isCore: false,
    recommended: true,
  },
  {
    id: "item_floor",
    spaceId: "space_living",
    spaceLabel: "거실",
    label: "바닥",
    labelI18n: { ko: "바닥", en: "Floor", zh: "地板", vi: "Sàn nhà" },
    icon: "🟫",
    sourceTier: "standard_fallback",
    fallbackItemId: "std_floor",
    isCore: false,
    recommended: true,
  },
  {
    id: "item_window",
    spaceId: "space_living",
    spaceLabel: "거실",
    label: "창문·샷시",
    labelI18n: { ko: "창문·샷시", en: "Window/frame", zh: "窗户", vi: "Cửa sổ" },
    icon: "🪟",
    sourceTier: "standard_fallback",
    fallbackItemId: "std_window",
    isCore: false,
    recommended: true,
  },
];

// 항목별 기록(촬영됨) — 3건. 저장 키 계약(role·capture_stage·hash·anchor·viewpoint) 채움.
export const DEMO_ITEM_RECORDS: ItemRecord[] = [
  {
    itemId: "item_aircon",
    photos: [
      {
        id: "ph_0001",
        itemId: "item_aircon",
        role: "wide",
        captureStage: "movein_window",
        capturedAt: "2026-06-30T11:20:00+09:00",
        serverReceivedAt: "2026-06-30T11:20:12+09:00",
        fileHash: "sha256:a1b2c3aircon-wide",
        edited: false,
        locationAnchorId: "anc_living_wall_e",
        viewpointId: "vp_living_01",
      },
      {
        id: "ph_0002",
        itemId: "item_aircon",
        role: "closeup",
        captureStage: "movein_window",
        capturedAt: "2026-06-30T11:21:00+09:00",
        serverReceivedAt: "2026-06-30T11:21:08+09:00",
        fileHash: "sha256:a1b2c3aircon-close",
        edited: false,
        locationAnchorId: "anc_living_wall_e",
        viewpointId: "vp_living_01",
      },
    ],
    memo: "송풍구 하단 미세 스크래치 있음",
    shareScope: "private",
    capturedAt: "2026-06-30T11:21:00+09:00",
    evidenceGrade: "primary",
  },
  {
    itemId: "item_fridge",
    photos: [
      {
        id: "ph_0003",
        itemId: "item_fridge",
        role: "wide",
        captureStage: "movein_window",
        capturedAt: "2026-06-30T11:35:00+09:00",
        serverReceivedAt: "2026-06-30T11:35:10+09:00",
        fileHash: "sha256:d4e5f6fridge-wide",
        edited: false,
        locationAnchorId: "anc_kitchen_builtin",
        viewpointId: "vp_kitchen_01",
      },
      {
        id: "ph_0004",
        itemId: "item_fridge",
        role: "closeup",
        captureStage: "movein_window",
        capturedAt: "2026-06-30T11:36:00+09:00",
        serverReceivedAt: "2026-06-30T11:36:09+09:00",
        fileHash: "sha256:d4e5f6fridge-close",
        edited: false,
        locationAnchorId: "anc_kitchen_builtin",
        viewpointId: "vp_kitchen_01",
      },
    ],
    shareScope: "private",
    capturedAt: "2026-06-30T11:36:00+09:00",
    evidenceGrade: "primary",
  },
  {
    itemId: "item_sink",
    photos: [
      {
        id: "ph_0005",
        itemId: "item_sink",
        role: "wide",
        captureStage: "movein_window",
        capturedAt: "2026-06-30T12:02:00+09:00",
        serverReceivedAt: "2026-06-30T12:02:11+09:00",
        fileHash: "sha256:g7h8i9sink-wide",
        edited: false,
        locationAnchorId: "anc_kitchen_sink",
        viewpointId: "vp_kitchen_02",
      },
    ],
    memo: "배수 연결부 물기 흔적 — 확인 필요",
    shareScope: "defect_submitted",
    shareDetail: "하자 1건에 제출됨",
    capturedAt: "2026-06-30T12:02:00+09:00",
    evidenceGrade: "primary",
  },
];
